import { editModes, GitProject, guid, MappedParameter, MappedParameters, Parameter, Parameters } from "@atomist/automation-client";
import { CodeTransform, CodeTransformRegistration } from "@atomist/sdm";
import { SlackMessage } from "@atomist/slack-messages";
import * as goals from "../../../fingerprints/index";
import { footer } from "../../support/util";

// ------------------------------
// update a project dependency
// ------------------------------

@Parameters()
export class ConfirmUpdateParameters {

    @Parameter({ required: false, displayable: false })
    public msgId?: string;

    @MappedParameter(MappedParameters.GitHubOwner)
    public owner: string;

    @MappedParameter(MappedParameters.GitHubRepository)
    public repo: string;

    @MappedParameter(MappedParameters.GitHubRepositoryProvider)
    public providerId: string;

    @Parameter({ required: true })
    public name: string;

    @Parameter({ required: true })
    public version: string;
}

const confirmUpdate: CodeTransform<ConfirmUpdateParameters> = async (p, cli) => {
    // await cli.addressChannels(`make an edit to the project in ${(p as GitProject).baseDir} to go to version ${cli.parameters.version}`);
    goals.edit((p as GitProject).baseDir, cli.parameters.name, cli.parameters.version);
    const message: SlackMessage = {
        attachments: [
            {
                author_name: "Library Update",
                author_icon: `https://images.atomist.com/rug/check-circle.gif?gif=${guid()}`,
                text: `Updating version to \`${cli.parameters.name}:${cli.parameters.version}\` in <https://github.com/${
                    cli.parameters.owner}/${cli.parameters.repo}|${cli.parameters.owner}/${cli.parameters.repo}>`,
                mrkdwn_in: ["text"],
                color: "#45B254",
                fallback: "none",
                footer: footer(),
            },
        ],
    };
    await cli.addressChannels(message);
    return p;
};

export const ConfirmUpdate: CodeTransformRegistration<ConfirmUpdateParameters> = {
    name: "LibraryImpactConfirmUpdate",
    description: "choose to raise a PR on the current project for a library version update",
    paramsMaker: ConfirmUpdateParameters,
    transformPresentation: ci => {
        const pr = new editModes.PullRequest(
            `library-impact-confirm-update-${Date.now()}`,
            `Update library ${ci.parameters.name} to ${ci.parameters.version}`,
            "Nudge generated by Atomist");
        (pr as any).autoMerge = {
            mode: editModes.AutoMergeMode.SuccessfulCheck,
        };
        return pr;
    },
    transform: confirmUpdate,
};
